spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_URL_DEV:newcycle}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}